### ISSUE TITLE
Error during Docker build

### ISSUE THREAD

**Issue by mathieubrglt** [opensourceBIM/voxel_server#1]
I'm trying to build with `docker build -t vox_serv .` but I'm stuck with this error at step 6 :
```
Step 6/22 : RUN CXXFLAGS="-O3 -march=native" BUILD_CFG=Release python build-all.py
 ---> Running in 0f7b5598fe48
```
When fetching python :
```
Fetching python-2.7.16...   
----------------------------------------------------------------------

----------------------------------------------------------------------
Traceback (most recent call last):
  File "build-all.py", line 515, in <module>
    build_dependency("python-%s%s" % (PYTHON_VERSION,abi_tag), "autoconf", PYTHON_CONFIGURE_ARGS + [unicode_conf], "http://www.python.org/ftp/python/%s/" % (PYTHON_VERSION,), "Python-%s.tgz" % (PYTHON_VERSION,))
  File "build-all.py", line 321, in build_dependency
    __check_call__(WGET + ["-O", download_name, url], cwd=build_dir)
  File "build-all.py", line 230, in __check_call__
    raise Exception("Command `%s` returned exit code %d" % (" ".join(cmds), proc.returncode))
Exception: Command `wget -q --no-check-certificate -O Python-2.7.16.tgz http://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz` returned exit code 4
The command '/bin/sh -c CXXFLAGS="-O3 -march=native" BUILD_CFG=Release python build-all.py' returned a non-zero code: 1

```

**Comment by aothms** [comment]
> Command `wget -q --no-check-certificate -O Python-2.7.16.tgz http://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz` returned exit code 4

Could it be it's simply related to network connectivity or something? Did you try simply rerunning the build?

**Comment by mathieubrglt** [comment]
I was correctly connected and I tried twice, then I added python3 to apt-get and it worked... I don't understand why
