### ISSUE TITLE
add RUN apt-get -y update && apt-get -y install libffi-dev in Dokerfile

### ISSUE THREAD

**Issue by bbrangeo** [opensourceBIM/voxel_server#2]
Hi, 

ERROR COMPILE PYTHON 3.7 :

SOLUTION : add RUN apt-get -y update && apt-get -y install libffi-dev in Dokerfile

```

Installing python-3.7.3...
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 20, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/download.py", line 37, in <module>
  File "/tmp/tmp62eh70wu/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/IfcOpenShell/build/Linux/x86_64/build/Python-3.7.3/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
make: *** [install] Error 1
```

**Comment by aothms** [comment]
> SOLUTION : add RUN apt-get -y update && apt-get -y install libffi-dev in Dokerfile

Thanks. Can you send a pull request then?

Alternatively, voxelization_toolkit supports IfcOpenShell v0.6.0 now as well. In that build script you can add `python build-all.py IfcGeom` so that only IfcGeom and its dependencies are built.
